export const SET_ACTIVE_SUPPLIER = 'SET_ACTIVE_SUPPLIER'
export const NEXT_SUPPLIER = 'NEXT_SUPPLIER'
export const PREV_SUPPLIER = 'PREV_SUPPLIER'
export const SET_ACTIVE_BY_INDEX = 'SET_ACTIVE_BY_INDEX'
